#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/banking_server?serverTimezone=Asia/Seoul
#    username: root
#    password: a6450307
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
##    hibernate.hbm2ddl.auto: update
#        hibernate:
#          ddl-auto: create
#    properties:
#      hibernate:
#        # show_sql: true
#        format_sql: true
##
##logging.level:
##  org.hibernate.SQL: debug
##  org.hibernate.type: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_server?serverTimezone=Asia/Seoul
    username: root
    password: a6450307
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
#    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
